version: 2.1
orbs:
  node: circleci/node@4.0.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    environment:
      - MONGO_URL: mongodb://localhost/image
    steps:
      - checkout
      - run: npm install
      - run: npm test
